#!/usr/bin/env python3
"""
Compare two Shopify theme export directories. Emits Markdown listing:
- per-directory added / removed / changed files (by SHA256 of contents)
- recursive counts for templates (*.json), sections, snippets

Usage:
  python3 scripts/diff_theme_exports.py OLD_THEME_DIR NEW_THEME_DIR > report.md
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

DIRS = ("templates", "sections", "snippets", "assets", "config", "layout", "locales")


def sha256_file(p: Path) -> str:
    h = hashlib.sha256()
    h.update(p.read_bytes())
    return h.hexdigest()


def collect_index(base: Path) -> dict[str, str]:
    idx: dict[str, str] = {}
    for sub in DIRS:
        root = base / sub
        if not root.is_dir():
            continue
        for p in root.rglob("*"):
            if p.is_file():
                rel = p.relative_to(base).as_posix()
                idx[rel] = sha256_file(p)
    return idx


def count_inventory(base: Path) -> dict[str, int]:
    def nfiles(pattern: str, under: str) -> int:
        r = base / under
        if not r.is_dir():
            return 0
        return sum(1 for p in r.rglob(pattern) if p.is_file())

    return {
        "templates_json": nfiles("*.json", "templates"),
        "sections_liquid": nfiles("*.liquid", "sections"),
        "snippets_liquid": nfiles("*.liquid", "snippets"),
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("old_dir", type=Path)
    ap.add_argument("new_dir", type=Path)
    args = ap.parse_args()
    old, new = args.old_dir.resolve(), args.new_dir.resolve()
    if not old.is_dir() or not new.is_dir():
        print("Both arguments must be directories.", file=sys.stderr)
        return 1

    old_i, new_i = collect_index(old), collect_index(new)
    ko, kn = set(old_i), set(new_i)
    added = sorted(kn - set(old_i))
    removed = sorted(set(old_i) - kn)
    changed = sorted(k for k in ko & kn if old_i[k] != new_i[k])

    title = f"Theme export diff: `{old.name}` → `{new.name}`"
    inv_o, inv_n = count_inventory(old), count_inventory(new)

    lines = [
        f"# {title}\n",
        "Generated by `scripts/diff_theme_exports.py`.\n",
        "## Inventory (recursive)\n",
        "| Metric | Old | New | Delta |",
        "|--------|-----|-----|-------|",
    ]
    for k in sorted(inv_o.keys()):
        o, n = inv_o[k], inv_n[k]
        lines.append(f"| {k} | {o} | {n} | {n - o:+d} |")
    lines.append("")

    lines.append("## Summary by top-level folder\n")
    lines.append("| Folder | Added | Removed | Changed |")
    lines.append("|--------|-------|---------|---------|")
    for sub in DIRS:
        a = [p for p in added if p.startswith(sub + "/")]
        r = [p for p in removed if p.startswith(sub + "/")]
        c = [p for p in changed if p.startswith(sub + "/")]
        lines.append(f"| {sub} | {len(a)} | {len(r)} | {len(c)} |")
    lines.append("")

    def block(name: str, paths: list[str]) -> None:
        lines.append(f"## {name} ({len(paths)})\n")
        if not paths:
            lines.append("_None._\n")
            return
        for p in paths:
            lines.append(f"- `{p}`")
        lines.append("")

    block("Added files", added)
    block("Removed files", removed)
    block("Changed files (same path, different content)", changed)

    sys.stdout.write("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
